all: arraymaker matrixmaker quicksort mergesort estandarsort selectionsort mmtradicional mmoptimizado strassen 

maker: arraymaker matrixmaker

quicksort: quicksort.cc
	g++ quicksort.cc -o  quicksort

mergesort: mergesort.cc
	g++  mergesort.cc -o mergesort

estandarsort: estandarsort.cc
	g++ estandarsort.cc -o estandarsort

selectionsort: selectionsort.cc
	g++ selectionsort.cc -o selectionsort

mmtradicional: mmtradicional.cc
	g++ mmtradicional.cc -o mmtradicional

mmoptimizado: mmoptimizado.cc
	g++ mmoptimizado.cc -o mmoptimizado

strassen: strassen.cc 
	g++ strassen.cc -o strassen

arraymaker: arraymaker.py
	python3 arraymaker.py

matrixmaker: matrixmaker.py
	python3 matrixmaker.py

clean:
	rm -rf *.o quicksort mergesort estandarsort selectionsort mmtradicional mmoptimizado strassen gmon.out
